name: tennis-analysis
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cccl=12.6.77
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.77
  - cuda-runtime=11.8.0
  - freetype=2.12.1
  - giflib=5.2.2
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - networkx=3.2.1
  - numpy-base=2.1.3
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pip=24.2
  - pysocks=1.7.1
  - python=3.10.14
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.2.2
    - aiofiles==23.2.1
    - annotated-types==0.7.0
    - anyio==4.4.0
    - asttokens==3.0.0
    - astunparse==1.6.3
    - attrs==25.3.0
    - backcall==0.2.0
    - beautifulsoup4==4.13.3
    - bleach==6.2.0
    - cachetools==5.5.2
    - click==8.1.7
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - decorator==5.2.1
    - defusedxml==0.7.1
    - docopt==0.6.2
    - easyocr==1.7.2
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastapi==0.115.5
    - fastjsonschema==2.21.1
    - ffmpy==0.4.0
    - filelock==3.16.0
    - flatbuffers==24.3.25
    - fonttools==4.53.1
    - fsspec==2024.9.0
    - gast==0.4.0
    - google-auth==2.38.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gradio==5.6.0
    - gradio-client==1.4.3
    - grpcio==1.71.0
    - h11==0.14.0
    - h5py==3.13.0
    - httpcore==1.0.5
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - humanfriendly==10.0
    - idna==3.8
    - imageio==2.37.0
    - importlib-resources==6.4.5
    - ipython==8.12.3
    - jedi==0.19.2
    - joblib==1.5.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - libclang==18.1.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - memory-profiler==0.61.0
    - mistune==3.1.3
    - ml-dtypes==0.5.1
    - namex==0.0.8
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - ninja==1.11.1.4
    - numpy==1.26.4
    - oauthlib==3.2.2
    - onnxruntime-gpu==1.18.1
    - opencv-contrib-python==4.11.0.86
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.11.0.86
    - opt-einsum==3.4.0
    - optree==0.15.0
    - orjson==3.10.7
    - packaging==24.1
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pipreqs==0.5.0
    - platformdirs==4.3.7
    - prompt-toolkit==3.0.50
    - protobuf==3.19.6
    - psutil==6.1.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pyclipper==1.3.0.post6
    - pydantic==2.9.1
    - pydantic-core==2.23.3
    - pydub==0.25.1
    - pygments==2.18.0
    - pympler==1.1
    - pyparsing==3.1.4
    - python-bidi==0.6.6
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.12
    - pytz==2024.2
    - pyzmq==26.4.0
    - referencing==0.36.2
    - requests-oauthlib==2.0.0
    - rich==13.8.1
    - rpds-py==0.24.0
    - rsa==4.9
    - ruff==0.6.4
    - safehttpx==0.1.1
    - scikit-image==0.25.2
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - semantic-version==2.10.0
    - shapely==2.1.0
    - shellingham==1.5.4
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - starlette==0.41.3
    - sympy==1.13.1
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow==2.8.0
    - termcolor==3.0.1
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.6.0
    - tifffile==2025.3.30
    - tinycss2==1.4.0
    - tomlkit==0.12.0
    - torch-dct==0.1.6
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - tornado==6.4.2
    - tqdm==4.66.5
    - traitlets==5.14.3
    - typer==0.12.5
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - uvicorn==0.30.6
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - websockets==12.0
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - yarg==0.1.9
prefix: C:\Users\zjw\.conda\envs\pose-prediction
